- zenpy/__init__.py
This is a small change that allows an OAuth2Session to be passed without requiring a password/token. Please let me know if you'd like anything else to be changed as well.
> Added support for OAuth2Session when creating a Zenpy object

- zenpy/lib/api.py
Was getting this:
```
>>> zp.users.requested(zp.users.me().id)
<zenpy.lib.generator.ResultGenerator object at 0x7f39e482b750>
>>> zp.users.assigned(zp.users.me().id)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/ec2-user/concord/local/lib/python2.7/site-packages/zenpy/lib/api.py", line 506, in assigned
return self._get_items(self.endpoint.assigned, 'ticket', user_id)
File "/home/ec2-user/concord/local/lib/python2.7/site-packages/zenpy/lib/api.py", line 83, in _get_items
return self._get_paginated(endpoint, object_type, *args, **kwargs)
File "/home/ec2-user/concord/local/lib/python2.7/site-packages/zenpy/lib/api.py", line 104, in _get_paginated
_json = self._query(endpoint=endpoint(*args, **kwargs))
TypeError: __call__() takes exactly 1 argument (2 …
```
> Specify "id=user_id" kwarg when getting tickets assigned for user.

- zenpy/lib/api.py
This adds an optional parameter target_name to allow the API user to set the filename inside Zendesk. For backward compatibility it retains the default method of using the file path to create the attachment filename.
> Allow user to specify attachment filename inside Zendesk

- docs/zenpy.rst
There should be no need to pass an email address when using an oauth token.
> Remove misleading doc

- zenpy/__init__.py
- zenpy/lib/api.py
Where I work, it would be a very bad thing to hit the rate limit. As such, I wanted a method to be able to proactively play things on the safe side (especially since some of my scripts are going to be aggressive on grabbing data).
When the `ratelimit` parameter is set (an integer value), instead of a straight `http_method` call being made from the `_call_api` method, the method `_ratelimit` will be used instead.
1. Execution Check
1. If `time_since_last_call` returns `None`, `time_since_last_call` returns >= 10 (seconds), or the value of the `X-Rate-Limit-Remaining` header from the previous response is >= the `ratelimit` parameter specified on client instantiation, the API call is made and the response stored.
1. If none of the above apply, `sleep` will be called until …
> Add optional ratelimit parameter

- zenpy/lib/endpoint.py
This allows zenpy to support the role filter when making API calls. Someone needs to do the same for permissions, if the maintainer believes this is the right approach to support filters.
> Support role filter in endpoint

- docs/zenpy.rst
- zenpy/lib/endpoint.py
This patch addresses permission_set filtering mentioned in #112 and performs documentation asked in #111 
**I did not test permission_set** since I don't have Enterprise, but the logic should be identical as far as I can tell.
> Permission_set filter, document filter

- zenpy/lib/endpoint.py
This should fix the bug for *_between that throws away data. I am currently using this fix to run my software. That being said, I discovered a bug in zendesk where a timezone that uses a "+" will return an error in zendesk and with a - it will work. 
Example:
https://subdomain.zendesk.com/api/v2/search.json?query=type:"ticket"+created>2015-09-01T12:00:00-00:00 works!
https://subdomain.zendesk.com/api/v2/search.json?query=type:"ticket"+created>2015-09-01T12:00:00+00:00 does not work
I notified Zendesk of the bug and here is their response (see engineer response at bottom):
(10:47:53 AM) Joshua Miller: No when I use a + timezone offset it does nto work
(10:48:09 AM) Joshua Miller: and when I use a - timezone offset it works
(10:48:32 AM) Joshua Miller: So I can do a search for UTC-05:00 …
> Fix for *_between throwing away time and time zone

- .gitignore
- zenpy/lib/endpoint.py
- zenpy/lib/generator.py
I have a sandbox store with only about 40 tickets. Every time I try to do `client.tickets()[0:1]` I'm getting a crash:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/lib/python3.6/site-packages/zenpy/lib/generator.py", line 86, in __getitem__
return self._handle_slice(item)
File "/lib/python3.6/site-packages/zenpy/lib/generator.py", line 99, in _handle_slice
if 'incremental' in self._response_json.get("next_page", ''):
TypeError: argument of type 'NoneType' is not iterable
```
It's because `next_page` key is there, but it's value is `None`. In other parts of the codebase we expect `next_page` to be `None`, but here we don't.
I tried to add some tests but we have quite sensitive data in our sandbox, I'm not sure how to obfuscate it.
Also this PR:
* adds …
> Fix generator to not crash if next_page is None

- zenpy/lib/cache.py
I've faced the same problem in my multi-thread script:
http://www.paulsprogrammingnotes.com/2016/08/python-cachetools-lrucache-keyerror.html
and solved it. 
Without this fix I constantly got many KeyErrors and now they have disappeared.
> Make cache thread-safe

- zenpy/lib/api.py
- zenpy/lib/request.py
Faced a problem - now Zendesk doesn't accept files with unknown extensions - returns error 422. Support has helped me, these files must have a special content-type - "application/*". But if I change the standard zenpy content type, Zendesk stops generate thumbnails for pictures, so it's not a solution.
My variant is to pass a content_type parameter when it is needed.
I had to change the very basic lib functions, hope my changes havn't broken something else :)
New upload style looks like this:
```
ct, enc = mimetypes.guess_type(file_name)
ct = 'application/*' if not ct
zenpy.attachments.upload(path, target_name=file_name, content_type = ct)
```
The old style has to work too:
`zenpy.attachments.upload(path, target_name=file_name)`
if you don't need custom content types
> Content type for custom attachment file exstensions

- zenpy/__init__.py
- zenpy/lib/api.py
Hi,
I've added a new value in Zenpy object to manage interval between two requests to Zendesk API. Default value is 10 sec
> adding request_interval instead of 10 sec hardcode value

- zenpy/lib/endpoint.py
Allow listing tickets by 'external_id' as per Zendesk's documentation. [Tickets - Core API](https://developer.zendesk.com/rest_api/docs/core/tickets#list-tickets-by-external-id)
> add support for listing tickets by external_id

- zenpy/lib/api.py
- zenpy/lib/request.py
Solved two problems:
1. Inline parameter wasn't used.
2. Setting file name and content type.
> Help center attachment issues

- .travis.yml
Python 3.4 end of life is in 24 days.
https://docs.python.org/devguide/index.html#branchstatus
> Travis CI: Add Python 3.7 and 3.8-dev

- docs/zenpy.rst
- requirements.dev
New entry to requirments dev allows to build html locally with
```
docs/make html
```
Otherwise theme error raised.
> Closes #291 Note and code example for high intensive job status parsing.

- zenpy/lib/api.py
- zenpy/lib/response.py
Added multiple job statuses parsing for a call like 
`job_ids = [...]`
`job_statuses = zenpy_client.job_status(ids=job_ids)`
Now it returns a collection under a key 'job_statuses'
> Multiple job statuses support

- zenpy/__init__.py
- zenpy/lib/api.py
- zenpy/lib/endpoint.py
- zenpy/lib/response.py
Added **zenpy.search.count(**) which takes all the same as **zenpy.search()** but returns count only.
Documentation: https://developer.zendesk.com/rest_api/docs/support/search#show-results-count
Usual **zenpy.search()** should not be affected, I hope :)
I need this functionality after last [changes to searching limits](https://developer.zendesk.com/rest_api/docs/support/search#results-limit).
> Search count

- zenpy/lib/api.py
- zenpy/lib/generator.py
- zenpy/lib/response.py
This PR has one enhancement and one fix.
I added a generator for Jira links using 'since_id' so we can paginate through all of the results. This should address https://github.com/facetoe/zenpy/issues/359.
I also fixed an issue where referencing a ticket from a Jira link would always fail. This was because it would build the API URL using the prefix for Jira links, 'api', instead of the prefix for tickets, 'api/v2'.
> Support for Jira Links API pagination and deserialization

- requirements.dev
- requirements.txt
- setup.py
- zenpy/lib/generator.py
- zenpy/lib/response.py
This closes #402 by changing `future` with `six` as dependency to support Python 2 and 3.
I added an explicit cast to integer for the `ceil()` function only if running on Python 2, this makes easier to remove the code in a future when the package drops support for this version.
This was tested on Python 2.7 and from 3.5 to 3.8.
> Replace future with six

- zenpy/lib/generator.py
- zenpy/lib/response.py
As was pointed out by @mvforgione in #400 the Jira Link generator I added in #389 did not respect `ticket_id` or `issue_id` filtering.
This change adds support for filtering by passing the raw requests response on initialization of `JiraLinkGenerator`. Using the requests response `get_next_page` is able to persist any filtering from the original requests.
> Support for filtering in the Jira Link generator.

- zenpy/lib/endpoint.py
- zenpy/lib/generator.py
Simple fix to use raw string literals in certain regex patterns containing backslashes. Fixes #416 .
> Address Python 3.7 deprecation warning on regex patterns. Fix #416

- tests/test_api/test_user_search_api.py
- zenpy/lib/api.py
- zenpy/lib/endpoint.py
I noticed the following endpoints are not yet supported:
`GET /api/v2/users/search.json?query={query}`
`GET /api/v2/users/search.json?external_id={external_id}`
[more info](https://developer.zendesk.com/rest_api/docs/support/users#search-users)
This PR adds `UserSearchApi` for this purpose. One thing I noticed is that when using the normal search endpoint (i.e. `client.search(email="hello@goodbye.com", type="user")`) users are not immediately searchable. from the [docs](https://developer.zendesk.com/rest_api/docs/support/search):
> "Note: It can take up to a few minutes for new tickets, users, and other resources
>     to be indexed for search. If new resources don't appear in your search results, wait
>     a few minutes and try again."
I've found that `/users/search.json` is a more …
> Adds user search

- zenpy/lib/request.py
This maintains the type checking done by `BaseZendeskRequest.check_type` but allows subclasses of `zenpy` objects.
> Allow subclasses of zenpy objects when checking type

- zenpy/lib/api.py
Zendesk sets the updater_id to -1 when the update is performed by an
audit. Just return None in this case instead of throwing an exception.
Closes #356
> Don't fail on audit updaters.

- zenpy/lib/generator.py
Looks like ZD uses "end_of_stream" not instead of null "next_page".
Closes #451
> Fix bug with infinite loop in incremental generator

- zenpy/lib/endpoint.py
datetime is a subclass of date so it needs to be processed first. Also, check value not key.
```
>>> isinstance(datetime.now(), date)
True
```
> Handle datetime correctly in search input

- docs/zenpy.rst
- zenpy/lib/api.py
- zenpy/lib/endpoint.py
- zenpy/lib/generator.py
- zenpy/lib/response.py
- zenpy/lib/util.py
- The [Zendesk API](https://developer.zendesk.com/rest_api/docs/support/incremental_export#cursor-based-incremental-exports) has added cursor-based pagination of incremental exports of the _Ticket_ model and recommends using this over time-based pagination for better performance and consistency.
- The _Ticket Audit_ model is the only other model that supports cursor based pagination in the Zendesk API.
- Zenpy implements cursor-based pagination for the _Ticket Audit_ model, but only implements time-based pagination for incremental exports of the _Ticket_ model.
- In `zenpy/lib/generator.py`, create the generic `TicketCursorGenerator` subclass to handle cursor based endpoints for `ticket` and `ticket_audit` objects. This generic subclass replaces the `TicketAuditGenerator`.
- Note that I …
> Add ticket cursor generator

- zenpy/lib/api.py
```python
def delete_zendesk_jira_links(zenpy_client, issue):
for link in zenpy_client.jira_links(issue_id=issue.id):
zenpy_client.jira_links.delete(link)
```
Returned the following JSON message on valid Jira Links: `{"error":"InvalidEndpoint","description":"Not found"} `
Turns out the Delete API for Jira Links is special - you can see more about it [here](https://developer.zendesk.com/api-reference/ticketing/jira/links/#delete-link).
I ended up overwriting the `delete` method in the `JiraLinkAPI` class to compensate for the unique delete URL for this resource.
I didn't find existing tests for `JiraLinkAPI` resources - but could look at creating some if desired in conjunction with this PR.
> fix: prevent InvalidEndpoint exception when deleting Jira links

- zenpy/lib/endpoint.py
It should be 'ids' according to the docs:
https://developer.zendesk.com/api-reference/ticketing/tickets/suspended_tickets/#recover-multiple-suspended-tickets
> it should be 'ids' according to the docs

- zenpy/__init__.py
This is a small fix to the exception message when both `password` and `token` are provided when initializing a `Zenpy` object.
> Fix exception message when password and token are provided

- zenpy/lib/api.py
https://support.zendesk.com/hc/en-us/community/posts/5609287554586-BUG-Get-articles-by-section-ID-requires-locale
> Fetching articles requires a locale

- zenpy/lib/api.py
Issue #571 
API endpoint returns single object.
> Fixes Issue-571: overly aggressive CBP campaign on single object

- zenpy/lib/endpoint.py
The first `__call__` is overridden by the second declaration immediately below it.
> remove redeclared method

- tests/test_api/test_other_zendesk_objects.py
- zenpy/__init__.py
Starts to fix Issue #651: begins with deprecation warning when using password
> Starts to fix Issue #651: begins with deprecation warning

- CHANGELOG.md
- pyproject.toml.XXX
- setup.py
- zenpy/__init__.py
- 
- Fixed issue https://github.com/facetoe/zenpy/issues/662
- ZenPy JIRA Links API now works on writes and base class supports singular/plural object deserialization.
> version 2.0.55 bump

- zenpy/lib/generator.py
Minor fixes to `SearchResponseLimitExceeded` error message.
- spacing added
- capitalized Zendesk
> closes #667 - Changes to error message text for SearchResponseLimitExceeded

- DEPLOY.md
direct invocation of `setup.py` is deprecated, and it is desirable to publish wheels
> publish wheels
