- zenpy/lib/api.py
- zenpy/lib/endpoint.py
https://developer.zendesk.com/rest_api/docs/core/organizations#search-organizations-by-external-id
> Locate Organizations by their external_id #36

- zenpy/lib/api.py
Hi
Please review my PR. I understand that probably I didn't get the idea of the library right and this logic should be put to some other place instead. I'm ready to change it whatever way you'll suggest
Thank you for your work
> Add attachments and thumbnails parsing to Api

- zenpy/lib/api.py
- zenpy/lib/endpoint.py
- zenpy/lib/generator.py
- zenpy/lib/manager.py
Add support for the [incremental ticket metrics api](https://developer.zendesk.com/rest_api/docs/core/incremental_export#incremental-ticket-metric-event-export)
> added support for incremental ticket metrics api

- zenpy/lib/api.py
Fixes issue #72
Signed-off-by: Anirudha Bose <ani07nov@gmail.com>
> Refactor upload method to also accept file-like objects

- zenpy/lib/api_objects.py
- zenpy/lib/manager.py
- zenpy/specification/agent_macro_reference.json
> Add support for AgentMacroReference.

- docs/zenpy.rst
- zenpy/__init__.py
- zenpy/lib/api.py
- zenpy/lib/exception.py
> Implement rate limit budget.

- zenpy/lib/api.py
When I was using this library, it was unclear if I would be getting all the tags in the system or for a particular ticket.
> clarify how the tags object is queried

- specification/zendesk/recipients.json
- specification/zendesk/responses.json
- zenpy/__init__.py
- zenpy/lib/api.py
- zenpy/lib/api_objects/__init__.py
- zenpy/lib/endpoint.py
- zenpy/lib/mapping.py
This PR adds incremental api for NPS; resolving issue #162 (Support NPS API) that I created.
Not sure if I need to make any additional change to it but, ping me if needed please. ✌️
> Implemented Zendesk NPS Incremental API

- specification/zendesk/automation.json
- zenpy/__init__.py
- zenpy/lib/api.py
- zenpy/lib/api_objects/__init__.py
- zenpy/lib/endpoint.py
- zenpy/lib/mapping.py
Now it's ready to use automations.
> Automations support

- zenpy/lib/api.py
- zenpy/lib/endpoint.py
The endpoint for creating a section was incorrect
> Right endpoint for hc section creation

- zenpy/lib/api.py
- zenpy/lib/endpoint.py
- zenpy/lib/mapping.py
Maybe not the best implementation, but works for me. Maybe somebody needs it too.
> Fixes #300. New method for completely ticket deletion added

- docs/conf.py
- docs/zenpy.rst
- setup.py
- zenpy/__init__.py
- zenpy/lib/api.py
* Fixed links in docs
* Fixed doc8 warnings about string length 
* Some typos fixed
* Some deprecated methods changed.
*
> Some other project work

- zenpy/lib/api.py
- zenpy/lib/endpoint.py
- zenpy/lib/generator.py
- zenpy/lib/response.py
Added an incremental API function to the Chat API wrapper
> Chat incremental API

- .circleci/config.yml
@facetoe not sure if you'll end up using it, or even if its the cleanest approach.. but i tested it and it works?
> Circleci testing

- zenpy/lib/api.py
- zenpy/lib/generator.py
- zenpy/lib/request.py
This is required for Python 3.8 compatibility
> Prefer collections.abc to collections for all ABCs

- zenpy/__init__.py
- zenpy/lib/endpoint.py
Add support for TicketMetricEvents. https://developer.zendesk.com/rest_api/docs/support/ticket_metric_events#instance_id
> add support for ticket metric events

- zenpy/lib/api.py
- zenpy/lib/request.py
https://github.com/facetoe/zenpy/issues/366
> Fix: identity update with incorrect payload

- tests/test_api/betamax/TestAttachmentUpload.test_upload_with_file_obj-upload-single.json
- tests/test_api/betamax/TestAttachmentUpload.test_upload_with_path_str-upload-single.json
- tests/test_api/betamax/TestAttachmentUpload.test_upload_with_pathlib_path-upload-single.json
- tests/test_api/test_create_update_delete_zendesk.py
- zenpy/lib/request.py
This should fix https://github.com/facetoe/zenpy/issues/379 - read there for context.
As this PR involves file system access, I've used the README.md in readonly mode as a file to try upload. If you have thoughts on how to clean that up, let me know @facetoe.
I've also fixed a compatibility issue with the new support for `PathLike` objects that causes the code to break in python 3.4 and 3.5.
> Fix bug in upload request handler and add tests

- tests/test_api/test_create_update_delete_zendesk.py
- zenpy/__init__.py
- zenpy/lib/api.py
Implements User Fields API to support CRUD operations on user fields
> Implement User Fields API to support CRUD operations

- zenpy/lib/api.py
- zenpy/lib/exception.py
- zenpy/lib/generator.py
> Handle Zendesk's new API search limits

- zenpy/lib/endpoint.py
> URL encode search query

- docs/zenpy.rst
> doc update to fix incorrect reference

- zenpy/lib/api.py
This makes it able to write to an in-memory file instead of a file on the disk, if chosen to.
> write the download to memory stream

- zenpy/__init__.py
- zenpy/lib/api.py
- zenpy/lib/endpoint.py
Released three endpoints from here: https://developer.zendesk.com/api-reference/voice/talk-partner-edition-api/reference/
> Add Talk Partner Edition API

- setup.py
Ref: https://stackoverflow.com/a/66443941/9599354
> Include license file in source

- requirements.dev
Added missing requirements inside dev like Jinja2, bf4 and yapf.
> Add missing dev requirements to dev.requirements

- README.md
- tests/test_api/betamax/TestSearchGenerator.test_search_generator_len.json
- tests/test_api/betamax/TestSearchGenerator.test_search_returns_search_result_generator.json
- zenpy/__init__.py
- zenpy/lib/api.py
- zenpy/lib/endpoint.py
- zenpy/lib/generator.py
- zenpy/lib/response.py
Added method:
```python
for ticket in zenpy_client.search_export(query='created>=1month', type='ticket'):
print(ticket.id)
```
Similar to `zenpy_client.search()`, but using [Search Export API](https://developer.zendesk.com/api-reference/ticketing/ticket-management/search/#export-search-results)
It may be handy if the limit of 1000 results is not sufficient.
Tests passed:
```
~# make unittest
nosetests -v --stop
Test that a single object can be created correctly. ... ok
test_single_delete_raises_recordnotfoundexception (test_api.test_create_update_delete_helpcentre.TestCategoryCreateUpdateDelete) ... ok
Test that a single object can be created correctly. ... ok
test_single_object_creation (test_api.test_create_update_delete_helpcentre.TestCategoryCreateUpdateDelete) ... ok …
```
> Added support for Search Export API

- zenpy/lib/api.py
- zenpy/lib/endpoint.py
Add support for endpoint /groups/assignable
https://developer.zendesk.com/api-reference/ticketing/groups/groups/#list-assignable-groups
> Add /groups/assignable endpoint support

- zenpy/__init__.py
Added a client "anonymous" attribute to skip session authentication. Defaults to false. This is useful for anonymous help center api calls.
> anon-client

- README.md
Aside for credentials, the Ticket object not imported in the quickstart example so doesn't run if tested
> Add import in README.md to make example workable

- DEPLOY.md
- pyproject.toml
- zenpy/lib/api.py
@Ptr314 Let's collaborate on this.
> Deploy notes and organization memberships is CBP

- pyproject.toml
- setup.py
- zenpy/__init__.py
> bump version

- zenpy/lib/endpoint.py
> satisfaction ratings nit

- tests/test_api/betamax/TicketsIncrementalTest.test_pagination.json
- tests/test_api/betamax/UsersIncrementalTest.test_pagination.json
- tests/test_api/fixtures/__init__.py
- tests/test_api/test_other_zendesk_objects.py
- zenpy/lib/api.py
- zenpy/lib/endpoint.py
@kovaacs started the 🔥 
Augments the incremental APIs and adds tests.
Fixes #572 
Please review @Ptr314
> users.incremental() doesn't behave like tickets.incremental()

- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_full_objects_create-create-multiple.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_half_objects_create-create-multiple.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_multiple_delete_full_objects-delete-many.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_multiple_delete_half_full_objects-delete-many.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_multiple_delete_raises_toomanyvaluesexception-delete-many.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_multiple_delete_single_object-delete-many.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_multiple_update_full_objects-tearDown.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_multiple_update_full_objects-update-many.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_multiple_update_half_full_objects-tearDown.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_multiple_update_half_full_objects-update-many.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_multiple_update_single_object-tearDown.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_multiple_update_single_object-update-many.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_raises_multiple_update_raises_toomanyvaluesexception-update-many.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_raises_toomanyvaluesexception_create-create-multiple.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_single_delete_raises_recordnotfoundexception-recordnotfound-delete.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_single_object_create-create-multiple.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_single_object_creation-create-single.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_single_object_creation-tearDown.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_single_object_deletion-delete-single.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_single_object_update-tearDown.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_single_object_update-update-single.json
- tests/test_api/betamax/TestUserCreateUpdateDeleteNoID.test_single_update_raises_recordnotfoundexception-recordnotfound-update.json
- tests/test_api/test_create_update_delete_zendesk.py
- zenpy/lib/api.py
- zenpy/lib/util.py
Fixes #578 and replaces None with string empty.
cc @krenzler
> #578 fixes None and replaces with string empty

- .circleci/config.yml
- Makefile
- requirements.dev
- ruff.toml
- zenpy/__init__.py
- zenpy/lib/api.py
- zenpy/lib/api_objects/__init__.py
- zenpy/lib/api_objects/zis_objects.py
- zenpy/lib/cache.py
- zenpy/lib/endpoint.py
- zenpy/lib/exception.py
- zenpy/lib/generator.py
- zenpy/lib/mapping.py
- zenpy/lib/proxy.py
- zenpy/lib/request.py
- zenpy/lib/response.py
- zenpy/lib/util.py
Thanks to @kovaacs  for the suggestion.  3.5/ 3.6 will need exclusionary workflows due to compatibility issues.
Addresses issue #583
> checkpoint RUFF

- tests/test_api/betamax/CategoryTest.test_pagination.json
- tests/test_api/betamax/TestCommunityTopicCreateUpdateDelete.test_single_delete_raises_recordnotfoundexception-recordnotfound-delete.json
- tests/test_api/betamax/TestCommunityTopicCreateUpdateDelete.test_single_object_creation-create-single.json
- tests/test_api/betamax/TestCommunityTopicCreateUpdateDelete.test_single_object_creation-tearDown.json
- tests/test_api/betamax/TestCommunityTopicCreateUpdateDelete.test_single_object_deletion-delete-single.json
- tests/test_api/betamax/TestCommunityTopicCreateUpdateDelete.test_single_object_update-tearDown.json
- tests/test_api/betamax/TestCommunityTopicCreateUpdateDelete.test_single_object_update-update-single.json
- tests/test_api/betamax/TestCommunityTopicCreateUpdateDelete.test_single_update_raises_recordnotfoundexception-recordnotfound-update.json
- tests/test_api/betamax/TopicTest.test_pagination.json
- tests/test_api/test_create_update_delete_helpcentre.py
- tests/test_api/test_other_zendesk_objects.py
Test only, adminstrative merge pending.
> adding HC tests

- zenpy/lib/util.py
> FIX: #590 import datetime

- README.md
- zenpy/lib/api.py
Fixed for https://github.com/facetoe/zenpy/issues/605
> Filtering webhooks invocations

- pyproject.toml.XXX
- setup.py
- zenpy/__init__.py
> new version 2.0.42

- tests/test_api/betamax/TestUserMe.test_users_me.json
- tests/test_api/test_other_zendesk_objects.py
- zenpy/lib/api.py
Fixes users.me and adds test to ensure it works.
> fixes users.me

- zenpy/lib/api.py
deleted users should be paginated
> deleted users should be paginated

- pyproject.toml.XXX
- setup.py
- zenpy/__init__.py
> bump_to_2.0.44

- zenpy/lib/api.py
dynamic content items supports CBP by default
> supports dynamic content CBP

- pyproject.toml.XXX
- setup.py
- zenpy/__init__.py
Bump 2.0.45
Fixes dynamic_content/items
> bump 2.0.45

- pyproject.toml.XXX
- setup.py
- zenpy/__init__.py
> Bumping to 2.0.49

- CHANGELOG.md
- pyproject.toml.XXX
- setup.py
- zenpy/__init__.py
- Added content_tag support to the library
- Added tests for those changes
- Fixed issue https://github.com/facetoe/zenpy/issues/633
- CONTRIBUTING.md (Better descriptions)
- Regenerated classes
- Generating classes now congnizant of execution context to facilitate generation
> version 2.0.50

- CHANGELOG.md
- pyproject.toml.XXX
- setup.py
- zenpy/__init__.py
- Added warning when using password, or error based on configuration
- Fixed issue https://github.com/facetoe/zenpy/issues/651
- ZenPy initializer will emit warning or error based on constructor configuration
> version 2.0.53

- zenpy/lib/api.py
Fixes issue #658 
Deprecates Zopim domain hardcoding on ChatAPI.
> Fixes issue #658 deprecate zopim domain on Chat APIs

- tests/test_api/betamax/TestJIRALink.test_create_jira_link.json
- tests/test_api/test_other_zendesk_objects.py
- zenpy/lib/generator.py
Add more flexibility in base class for object type for response processing.
object_type='link' COULD be 
```links```
or
```link```
> Fix: Issue #662 add more flexibility in base class for object type

- CHANGELOG.md
- pyproject.toml.XXX
- setup.py
- zenpy/__init__.py
- 
- Fixed issue https://github.com/facetoe/zenpy/issues/668
- Updates error message and build process and documentation of that build process.
> bumps to 2.0.56

- zenpy/lib/generator.py
> generator: fix runaway memory usage
